# Generated by Django 3.2.4 on 2021-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_caption'),
        ('accounts', '0002_auto_20210617_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='skill',
            new_name='interest',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_posts',
            field=models.ManyToManyField(to='post.Post'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='topic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.TopicTag'),
        ),
    ]
