# Generated by Django 3.2.4 on 2021-06-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_saved_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='topic',
        ),
    ]
