# Generated by Django 3.2.4 on 2021-06-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210621_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='topic',
            field=models.ManyToManyField(blank=True, to='accounts.TopicTag'),
        ),
    ]
