# Generated by Django 3.2.4 on 2021-06-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='interest',
            new_name='intrest',
        ),
    ]
