# Generated by Django 3.2.4 on 2021-07-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210714_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='viewed_by',
        ),
    ]
