# Generated by Django 3.2.4 on 2021-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_interest_userprofile_intrest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='intrest',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intrest',
            field=models.ManyToManyField(blank=True, related_name='profile_intrest', to='accounts.TopicTag'),
        ),
    ]
