# Generated by Django 3.2.4 on 2021-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
    ]
