# Generated by Django 3.2.4 on 2021-07-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_private_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follow_requests',
            new_name='followers_requests',
        ),
    ]
